### ISSUE TITLE
Unable to find valid certification path to requested target. Install failed

### ISSUE THREAD

**Issue by edudutra7** [radimitrov/CSharpShellApp#364] opened 2024-02-02 23:10 UTC
NU3012: Package 'Newtonsoft.Json 13.0.3' from 'https://api.nuget.org/v3/index.json': The author primary signature found a chain building issue: PartialChain: unable to find valid certification path to requested target. Install failed

**Comment by KUNGERMOoN** [comment] 2024-02-03 09:09
I have a similar problem when installing Microsoft.CodeAnalysis.CSharp package.
Here's the end of nuget output:
```
Acquiring lock for the installation of System.Runtime.CompilerServices. Unsafe 6.0.0 Acquired lock for the installation of System.Runtime.CompilerServices. Unsafe 6.0.0

PackageSignatureVerificationLog:

Packageldentity: System.Numerics. Vectors.4.5.0

Source: https://api.nuget.org/v3/index.json

PackageSignatureValidity: False

PackageSignatureVerificationLog:

Packageldentity: System.Buffers.4.5.1

Source: https://api.nuget.org/v3/index.json

PackageSignatureValidity: False

NU3012: Package 'System.Buffers 4.5.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature found a chain building issue: PartialChain: unable to find valid certification path to requested target NU3028: Package 'System.Buffers 4.5.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: PartialChain: unable to find valid certification path to requested target NU3012: Package 'System.Buffers 4.5.1' from source 'https://api.nuget.org/v3/index.json': The repository countersignature found a chain building issue: PartialChain: unable to find valid certification path to requested target NU3028: Package 'System.Buffers 4.5.1' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: PartialChain: unable to find valid certification path to requested target PackageSignatureVerificationLog:

Packageldentity: System.Runtime.CompilerServices.Unsafe.6.0.0 Source: https://api.nuget.org/v3/index.json

PackageSignatureValidity: False

Install failed. Rolling back...

Executing nuget actions took 1.4 sec
```

**Comment by radimitrov** [comment] 2024-02-03 10:56
Unfortunately shortly put this is likely caused by the network class changes from the Xamarin.Android to .NET 6/7/8 Microsoft migration and the root cause will probably never be fixed. I'm working on implementing a workaround.

**Comment by radimitrov** [comment] 2024-02-19 15:10
The issue is fixed now. Next update should be tomorrow.

**Closed** 2024-03-06 15:08 UTC
