### ISSUE TITLE
Request : Ability to open project in external hard drives (e.g. SDCARD)

### ISSUE THREAD

**Issue by equin0X35** [radimitrov/CSharpShellApp#348] opened 2023-11-26 02:39 UTC
it could be better if the a support external storage. is this possible? if so, why not?

**Comment by equin0X35** [comment] 2023-12-02 02:56
i see, accessing file in the external storage might be slower. I dont really have any a knowledge of it, but, it gain access to the sdcard using AndroidX.DocumentFile  and use System.IO for io operations. However, seeing the io operation performace decreases is not good.

**Comment by radimitrov** [comment] 2024-02-02 09:18
I will finally be able to start implementing this within a few days. Could take anywhere from 3 weeks to over 2 months depending on issues along the way and time. Hopefully less and not more.

There will be an update here again when the storage wrapper is fully functional and I begin integration with the app. And another one when that is finished and tested. 

The end result will still work under scoped storage for external storage. However in the file manager/picker UI that will be abstracted to a drop down list with the ability to add new root folders. Note that Android doesn't allow the storage root to be used so there are still a few inconvenient limits since folders will have to be added one by one or have the same parent folder. 

I'm also pinning this issue to act as a sort of an announcement.

**Comment by radimitrov** [comment] 2024-02-06 12:40
I'm going to have to push the few days start a bit more, at least until this [new priority issue](https://github.com/radimitrov/CSharpShellApp/issues/364) is fixed

**Comment by radimitrov** [comment] 2024-04-28 04:01
Life stuff happened and I wasn't really able to work on this as intended. However I did implement support for "MANAGE_EXTERNAL_STORAGE" permission - check the top of the file manager or project open window. It looks like Google approved the update 2 days ago. Hopefully they won't revoke this.
For now there won't be SD card support for working with projects directly - only the device internal storage. I'm considering this issue solved and closing it along with #325 #344 #325 #292

**Closed by radimitrov** 2024-04-28 04:01 UTC
Labels: enhancement
